Allow group <group-name> to manage instance-family in <location>
Allow group <group-name> to use subnets in <location>
Allow group <group-name> to manage virtual-network-family in <location>
Allow group <group-name> to inspect compartments in <location>
Allow group <group-name> to use vnics in <location>
Allow group <group-name> to use network-security-groups  in <location>
Allow group <group-name> to use private-ips  in <location>
Allow group <group-name> to manage public-ips  in <location>
Allow group <group-name> to manage volume-family in <location>
Allow group <group-name> to manage cluster-family in <location>
Allow group acme-dev-team to manage vcns in <location>
Allow group acme-dev-team to manage subnets in <location>
Allow group acme-dev-team to manage internet-gateways in <location>
Allow group acme-dev-team to manage nat-gateways in <location>
Allow group acme-dev-team to manage route-tables in <location>
Allow group acme-dev-team to manage security-lists in <location>
Allow group acme-dev-team-cluster-viewers to inspect clusters in <location>
Allow group acme-dev-team-pool-admins to use cluster-node-pools in <location>
Allow group acme-dev-team-auditors to read cluster-work-requests in <location>
Allow group acme-dev-team-sgw to manage service-gateways in <location>
Allow group acme-dev-team to use cloud-shell in <location>
Allow group acme-dev-team to read vaults in <location>
Allow group acme-dev-team to read keys in <location>
Allow group acme-dev-team to use compute-capacity-reservations in <location>
Allow group acme-dev-team to read metrics in <location>
